# Generated by Django 4.1 on 2023-12-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='city',
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formresponse',
            name='contact',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formresponse',
            name='country',
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formresponse',
            name='name',
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formresponse',
            name='profession',
            field=models.CharField(default=-1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formresponse',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='vol',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='volas',
            field=models.CharField(choices=[('ant', 'an Active Ant'), ('bird', 'a Speedy Sparrow'), ('ele', 'an Electric Elephant')], default=-1, max_length=4),
            preserve_default=False,
        ),
    ]
