# Generated by Django 4.1 on 2023-12-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_formresponse_city_formresponse_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='city',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='contact',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='country',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='profession',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='volas',
            field=models.CharField(choices=[('ant', 'an Active Ant'), ('bird', 'a Speedy Sparrow'), ('ele', 'an Electric Elephant')], default=0, max_length=4),
        ),
    ]
